Feature: Excel, keep table output of previous worksheet
nfdi4plants/Swate pull request #461
Opened 2024-07-04 09:21 UTC by Etschbeijer

Closes #448

2024-07-04 09:22 UTC, Etschbeijer commented
1st table
![345032464-0e4dd306-749c-437d-891e-266cbb91145a-1](https://github.com/nfdi4plants/Swate/assets/30893791/719d785e-ae0f-41d9-9061-3d0bdf6e019b)

2nd table
![345033053-895583b8-ef8e-4f04-87da-2c7ebde8283e](https://github.com/nfdi4plants/Swate/assets/30893791/acdc577d-ae00-4a8d-92b7-afe21eca2d3c)

2024-07-08 07:22 UTC, Freymaurer requested changes

2024-07-08 07:22 UTC, Freymaurer commented on src/Client/OfficeInterop/OfficeInterop.fs
> +        static member arcTableFromExcelTableName (tableName:string, context:RequestContext) =
name can be shortened `ArcTable.arcTableFromExcelTableName` duplicates arctable. Can be shortened to `ArcTable.fromExcelTableName` without loosing information

2024-07-08 07:22 UTC, Freymaurer commented on src/Client/OfficeInterop/OfficeInterop.fs
> +            let! result = ArcTable.arcTableFromExcelTableName("", context)
what does this logic do? Why do we get an arctable from ""-name. Shouldn't this be tryGet? With Some/None?

2024-07-08 07:22 UTC, Freymaurer commented on src/Client/OfficeInterop/OfficeInterop.fs
> +                if diff > 0 then // table larger than values -> Delete rows to reduce inMemoryTable size to previous table size
We adjust exel table not in-memory table!

2024-07-08 07:22 UTC, Freymaurer commented on src/Client/OfficeInterop/OfficeInterop.fs
> +        let newColValues =
We compare values to rows.count, are we sure that rows.count excludes header row?

2024-07-08 07:22 UTC, Freymaurer commented on src/Client/OfficeInterop/OfficeInterop.fs
> +            let logging = InteropLogging.Msg.create InteropLogging.Info (sprintf "Annotation Table created in [%s] with dimensions 2c x (%.0f + 1h)r." tableRange.address (6. - 1.))
Why do we hardcode rowCount to 6?

2024-07-08 08:07 UTC, Freymaurer approved these changes

2024-07-08 08:07 UTC, merged